comment:
  layout: header, changes, diff
coverage:
  status: {}
  notify:
    webhook:
      default: http://requestb.in/toh444to
        url: null
        threshold: null
        branches: null
        only_pulls: null
